# Generated by Django 3.2 on 2023-02-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230219_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_excluding_offer',
        ),
    ]
